name: Build and Release

on:
  push:
    branch:
    - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.24'
    - run: go build -o nftables-api main.go
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "nftables-api"
